name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven and analyze
        run: mvn -B verify -Dmaven.test.failure.ignore=true

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v5

      - name: Report Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Tests
          path: "**/target/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: true
